name: Backend CI

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install deps (npm ci)
        run: npm ci

      - name: Lint (eslint)
        run: npm run lint --if-present

      - name: Typecheck (tsc)
        run: |
          if npm run -s typecheck >/dev/null 2>&1; then
            npm run typecheck
          else
            npx tsc -p tsconfig.json --noEmit
          fi

      - name: Tests (vitest)
        run: npm test --if-present

      - name: Build (ts -> dist)
        run: npm run build

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist
          if-no-files-found: error
          retention-days: 5

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: |
            backend-ci:${{ github.sha }}
