name: Release & Deploy

on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_backend: ${{ steps.image.outputs.IMAGE_BACKEND }}
      tag: ${{ steps.vars.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve IMAGE_BACKEND
        id: image
        shell: bash
        run: |
          set -euo pipefail
          OWNER_LOWER="$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')"
          IMAGE_BACKEND="${{ vars.IMAGE_BACKEND }}"
          if [ -z "${IMAGE_BACKEND}" ]; then
            IMAGE_BACKEND="ghcr.io/${OWNER_LOWER}/todo-backend"
          fi
          echo "IMAGE_BACKEND=${IMAGE_BACKEND}" >> "$GITHUB_OUTPUT"
          echo "Using IMAGE_BACKEND=${IMAGE_BACKEND}"

      - name: Log in to GHCR (push)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version tags
        id: vars
        run: |
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "TAG_LATEST=latest" >> $GITHUB_OUTPUT
          echo "Building tags: ${{ steps.image.outputs.IMAGE_BACKEND }}:${GITHUB_REF_NAME} and :latest"

      - name: Build & push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ steps.image.outputs.IMAGE_BACKEND }}:${{ steps.vars.outputs.TAG }}
            ${{ steps.image.outputs.IMAGE_BACKEND }}:${{ steps.vars.outputs.TAG_LATEST }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Collect known_hosts for host
        id: kh
        shell: bash
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          set -euo pipefail
          KH="$(ssh-keyscan -T 10 -p 22 "$SSH_HOST" 2>/dev/null)"
          [ -n "$KH" ] || { echo "ssh-keyscan empty"; exit 1; }
          { echo "KNOWN_HOSTS<<EOF"; echo "$KH"; echo "EOF"; } >> "$GITHUB_OUTPUT"

      - name: Setup CI SSH key & known_hosts
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ steps.kh.outputs.KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Deploy over SSH (forced command on server)
        shell: bash
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          set -euo pipefail
          ssh -o BatchMode=yes -o StrictHostKeyChecking=yes "${SSH_USER}@${SSH_HOST}"

  create-release:
    runs-on: ubuntu-latest
    needs: [build-and-push, deploy]
    if: ${{ needs.deploy.result == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout (need git history & files)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare changelog for this tag
        id: changelog
        shell: bash
        env:
          TAG: ${{ needs.build-and-push.outputs.tag }}   # vX.Y.Z
        run: |
          set -euo pipefail

          # Найдём предыдущий тег (если есть)
          PREV_TAG="$(git describe --tags --abbrev=0 "${TAG}^" 2>/dev/null || true)"
          echo "Current tag: ${TAG}"
          echo "Previous tag: ${PREV_TAG:-<none>}"

          if [ -f CHANGELOG.md ]; then
            echo "[info] Using CHANGELOG.md and extracting section for ${TAG}"
            awk -v tag="${TAG}" '
              BEGIN { start=0 }
              /^##[[:space:]]*(\[[Vv]?[0-9]+\.[0-9]+\.[0-9]+\]|[Vv]?[0-9]+\.[0-9]+\.[0-9]+)/ {
                if (start==1) exit
                line=$0
                gsub(/[\[\]]/,"",line)
                l=line; t=tag
                gsub(/V/,"v",l); gsub(/V/,"v",t)
                if (index(l, t) > 0) { start=1 }
              }
              { if (start==1) print }
            ' CHANGELOG.md > CHANGELOG_RELEASE.md

            if [ ! -s CHANGELOG_RELEASE.md ]; then
              echo "[warn] Section for ${TAG} not found in CHANGELOG.md. Will fallback to git log."
            else
              echo "[ok] Extracted section from CHANGELOG.md"
            fi
          fi

          if [ ! -s CHANGELOG_RELEASE.md ]; then
            echo "[info] Building changelog from git log..."

            {
              echo "## ${TAG}"
              echo
              if [ -n "${PREV_TAG}" ]; then
                echo "_Changes since ${PREV_TAG}_"
                echo
                RANGE="${PREV_TAG}..${TAG}"
              else
                echo "_Initial release_"
                echo
                RANGE="${TAG}"
              fi

              echo "### Merged Pull Requests"
              MERGES="$(git log --merges --pretty=format:'- %s (%h)' "${RANGE}" | sed 's/Merge pull request /PR #/I' || true)"
              if [ -n "${MERGES}" ]; then
                echo "${MERGES}"
              else
                echo "- (none)"
              fi
              echo

              echo "### Commits"
              COMMITS="$(git log --pretty=format:'- %s (%h)' --no-merges "${RANGE}" || true)"
              if [ -n "${COMMITS}" ]; then
                echo "${COMMITS}"
              else
                echo "- (none)"
              fi
              echo
            } > CHANGELOG_RELEASE.md
          fi

          echo "[preview] ===== CHANGELOG_RELEASE.md ====="
          sed -n '1,120p' CHANGELOG_RELEASE.md
          echo "========================================"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build-and-push.outputs.tag }}
          name: Release ${{ needs.build-and-push.outputs.tag }}
          body_path: CHANGELOG_RELEASE.md
          files: |
            CHANGELOG_RELEASE.md

      - name: Print release info
        run: |
          echo "Released ${{ needs.build-and-push.outputs.image_backend }}:${{ needs.build-and-push.outputs.tag }}"
